version: '3'

services:
  logspout:
    build:
      context: logspout
    environment:
      ROUTE_URIS: logstash://logstash:5000
      LOGSTASH_TAGS: docker-elk
      LOGSPOUT: ignore
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - elk
    depends_on:
      - logstash
    restart: on-failure

  logstash:
    image: docker.elastic.co/logstash/logstash:7.1.1
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash-pipeline.conf:/usr/share/logstash/pipeline/pipline.conf:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      LOGSPOUT: ignore
    networks:
      - elk
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearchData:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    volumes:
     - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      LOGSPOUT: ignore
    networks:
      - elk
    depends_on:
      - elasticsearch

volumes:
  elasticsearchData:

networks:
  elk:
    driver: bridge
